### ISSUE TITLE
Doubt, temporal modulation

### ISSUE THREAD

**Issue by mjm522** [baxter-flowers/promplib#2]
Fantastic work, the code is simple and readable. 

Just got started reading with PromP and playing with this code.

I couldn't find temporal modulation implemented. Is there a quick way to do it. Since in this code base, the time dependence is taken direct, self.x = np.linspace(0, 1, numSamples), a simple scaling of this may not fix it. 

Could you please give me some insights on adding that feature.

Best,

Mike

**Comment by ymollard** [comment]
It depends what you mean and what you need. At first sight I see two different interpretations of your question:

 1. I want to modulate the output time (e.g. I want to slow down when the gripper approaches the table)
 2. I want to modulate the input time (e.g. my input demos are too poorly synchronized to be merged within a single gaussian mixture)

 **How?** In both cases consists not into distorting the time vector you mentioned (which remains [`n_samples=100`](https://github.com/baxter-flowers/promplib/blob/db7b26f2fc8cc55dee1a8c96d4d63bd63ac4c80d/src/promp/promp.py#L145) samples) but into distorting associated joint angles of every sample in order to take into account time deformation. 
You just compose motions with some deformation function. Problem 1. assumes that you know the deformation as an input, while 2. requires some method of syncing motions adequately to your usecase (can be several key points all along the motion?). 

**When?** This would be done [when adding a new demo](https://github.com/baxter-flowers/promplib/blob/db7b26f2fc8cc55dee1a8c96d4d63bd63ac4c80d/src/promp/promp.py#L164) for problem 2. or [when outputting a new motion](https://github.com/baxter-flowers/promplib/blob/db7b26f2fc8cc55dee1a8c96d4d63bd63ac4c80d/src/promp/promp.py#L273) for problem 1.

**Comment by mjm522** [comment]
Hi @ymollard,

Thanks a lot for the reply. Sorry for making you confused on the question. I followed what you have mentioned above. 

My question is on a section in the [paper](https://papers.nips.cc/paper/5177-probabilistic-movement-primitives.pdf) given on page 3. I am attaching a screenshot of the section here as a reference. 
![tempmodulation](https://user-images.githubusercontent.com/15670626/34911570-22385d6e-f8c5-11e7-8903-049d01b9ceac.png)

Though the results of this description were not shown in that paper, it did come out in a [later paper](http://www.ausy.tu-darmstadt.de/uploads/Team/AlexandrosParaschos/promps_auro.pdf) which you may have already seen. The result from that paper is also shown here as a reference.
![tempmodulationfig](https://user-images.githubusercontent.com/15670626/34911585-558e29b4-f8c5-11e7-8889-48c2f28b9aa4.png) 

I was hoping to get such a behavior. Is it possible in the existing code base? Since in this code base, 
self.x is an explicit function of time. Thanks for your time.

Best,

Michael Mathew

**Comment by ymollard** [comment]
This corresponds to my case 1 but is even simpler since deformation is uniform. A quick hack is just increase or decrease the motion duration [in parameter here](https://github.com/baxter-flowers/promplib/blob/db7b26f2fc8cc55dee1a8c96d4d63bd63ac4c80d/src/promp/ros/ros.py#L217).
This does not happen in class `ProMP` since this class has no notion of time (in seconds), but the ROS overlay does.

**Comment by mjm522** [comment]
Hi, 
I was able to achieve the temporal modulation by making self.x as a funciton to t instead of using the t directly. As specified in the class below. 


```
class Phase():
    """
    Utility funciton to generate phase of a
    trajectory
    """

    def __init__(self, dt=0.01, phase_speed=1., time_steps=200):

        self._dt =  dt
        self._phase_start = -dt
        self._time_steps = time_steps
        self._phase_end = self._phase_start + self._time_steps*dt

        #derivative of phase variable
        Dz  = np.ones(time_steps)*phase_speed

        #phase
        z   = np.cumsum(Dz)*dt

        #second derivative of phase variable
        DDz = np.diff(Dz)/dt
        DDz = np.hstack([DDz, DDz[-1]])

        self._z   = z
        self._Dz  = Dz
        self._DDz = DDz

    def get_phase_from_time(self, time_steps):
        return time_steps/self._phase_end

    def __call__(self):
        return self
```

Basically, you get temporal scaling by specifying different phase speeds.Values < 1 would speed up the phase and values > 1 slow it down.

I am closing the issue now. Thanks for the support.

Best,
Michael
